version: '3'

services:
  python:
    build: ./python-interactive
    container_name: python
    platform: linux/amd64
    env_file: .env
    restart: on-failure
    # depends_on:
    #   - rabbitmq
    # links:
    #   - rabbitmq
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - ./python-interactive/:/srv
