version: '3'

services:
  python-text-to-dwc:
    build: .
    container_name: non-ai-text-to-dwc
    platform: linux/amd64
    env_file: ../.env
    restart: on-failure
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./code:/srv
